# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\adamb\OneDrive\Documents\Scripts\Python\Utilities\time_lord\ui\time_lord_reports.ui'
#
# Created: Fri Dec 13 14:44:29 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Time_Lord_Reports(object):
    def setupUi(self, Time_Lord_Reports):
        Time_Lord_Reports.setObjectName("Time_Lord_Reports")
        Time_Lord_Reports.resize(1269, 711)
        Time_Lord_Reports.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(230, 230, 230);")
        self.centralwidget = QtGui.QWidget(Time_Lord_Reports)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_time_label = QtGui.QLabel(self.centralwidget)
        self.start_time_label.setObjectName("start_time_label")
        self.verticalLayout.addWidget(self.start_time_label)
        self.start_time = QtGui.QDateTimeEdit(self.centralwidget)
        self.start_time.setObjectName("start_time")
        self.verticalLayout.addWidget(self.start_time)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.end_time = QtGui.QDateTimeEdit(self.centralwidget)
        self.end_time.setObjectName("end_time")
        self.verticalLayout_2.addWidget(self.end_time)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.primary_org_label = QtGui.QLabel(self.centralwidget)
        self.primary_org_label.setObjectName("primary_org_label")
        self.verticalLayout_3.addWidget(self.primary_org_label)
        self.primary_org = QtGui.QComboBox(self.centralwidget)
        self.primary_org.setObjectName("primary_org")
        self.primary_org.addItem("")
        self.primary_org.addItem("")
        self.primary_org.addItem("")
        self.primary_org.addItem("")
        self.primary_org.addItem("")
        self.primary_org.addItem("")
        self.primary_org.addItem("")
        self.verticalLayout_3.addWidget(self.primary_org)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.secondary_org_label = QtGui.QLabel(self.centralwidget)
        self.secondary_org_label.setObjectName("secondary_org_label")
        self.verticalLayout_4.addWidget(self.secondary_org_label)
        self.secondary_org = QtGui.QComboBox(self.centralwidget)
        self.secondary_org.setObjectName("secondary_org")
        self.secondary_org.addItem("")
        self.verticalLayout_4.addWidget(self.secondary_org)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.trinary_org_label = QtGui.QLabel(self.centralwidget)
        self.trinary_org_label.setObjectName("trinary_org_label")
        self.verticalLayout_5.addWidget(self.trinary_org_label)
        self.trinary_org = QtGui.QComboBox(self.centralwidget)
        self.trinary_org.setObjectName("trinary_org")
        self.trinary_org.addItem("")
        self.verticalLayout_5.addWidget(self.trinary_org)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.run_btn = QtGui.QPushButton(self.centralwidget)
        self.run_btn.setObjectName("run_btn")
        self.horizontalLayout.addWidget(self.run_btn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.output_table = QtGui.QTableWidget(self.centralwidget)
        self.output_table.setObjectName("output_table")
        self.output_table.setColumnCount(0)
        self.output_table.setRowCount(0)
        self.verticalLayout_6.addWidget(self.output_table)
        Time_Lord_Reports.setCentralWidget(self.centralwidget)

        self.retranslateUi(Time_Lord_Reports)
        QtCore.QMetaObject.connectSlotsByName(Time_Lord_Reports)

    def retranslateUi(self, Time_Lord_Reports):
        Time_Lord_Reports.setWindowTitle(QtGui.QApplication.translate("Time_Lord_Reports", "Time Lord Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Time_Lord_Reports", "Time Lord Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.start_time_label.setText(QtGui.QApplication.translate("Time_Lord_Reports", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Time_Lord_Reports", "End Time", None, QtGui.QApplication.UnicodeUTF8))
        self.primary_org_label.setText(QtGui.QApplication.translate("Time_Lord_Reports", "Primary Organizer", None, QtGui.QApplication.UnicodeUTF8))
        self.primary_org.setItemText(0, QtGui.QApplication.translate("Time_Lord_Reports", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.primary_org.setItemText(1, QtGui.QApplication.translate("Time_Lord_Reports", "Artists", None, QtGui.QApplication.UnicodeUTF8))
        self.primary_org.setItemText(2, QtGui.QApplication.translate("Time_Lord_Reports", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.primary_org.setItemText(3, QtGui.QApplication.translate("Time_Lord_Reports", "Entities (Assets)", None, QtGui.QApplication.UnicodeUTF8))
        self.primary_org.setItemText(4, QtGui.QApplication.translate("Time_Lord_Reports", "Entities (Shots)", None, QtGui.QApplication.UnicodeUTF8))
        self.primary_org.setItemText(5, QtGui.QApplication.translate("Time_Lord_Reports", "All Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.primary_org.setItemText(6, QtGui.QApplication.translate("Time_Lord_Reports", "Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.secondary_org_label.setText(QtGui.QApplication.translate("Time_Lord_Reports", "Secondary Organizer", None, QtGui.QApplication.UnicodeUTF8))
        self.secondary_org.setItemText(0, QtGui.QApplication.translate("Time_Lord_Reports", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.trinary_org_label.setText(QtGui.QApplication.translate("Time_Lord_Reports", "Trinary Organizer", None, QtGui.QApplication.UnicodeUTF8))
        self.trinary_org.setItemText(0, QtGui.QApplication.translate("Time_Lord_Reports", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.run_btn.setText(QtGui.QApplication.translate("Time_Lord_Reports", "Run", None, QtGui.QApplication.UnicodeUTF8))

