# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\adamb\OneDrive\Documents\Scripts\Python\Utilities\time_lord\ui\time_lord_sheets.ui'
#
# Created: Wed Jan 29 16:51:24 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtGui, QtCore, QtWidgets


class Ui_TimeSheets(object):
    def setupUi(self, TimeSheets):
        TimeSheets.setObjectName("TimeSheets")
        TimeSheets.resize(1070, 571)
        TimeSheets.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(230, 230, 230);")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(TimeSheets)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.title = QtWidgets.QLabel(TimeSheets)
        self.title.setToolTip("")
        self.title.setStyleSheet("font: 24pt \"SeriaSansPro\";")
        self.title.setObjectName("title")
        self.horizontalLayout_8.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.todays_total_label = QtWidgets.QLabel(TimeSheets)
        self.todays_total_label.setObjectName("todays_total_label")
        self.horizontalLayout_6.addWidget(self.todays_total_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.todays_total = QtWidgets.QLabel(TimeSheets)
        self.todays_total.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.todays_total.setObjectName("todays_total")
        self.horizontalLayout_6.addWidget(self.todays_total)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.weeks_total_label = QtWidgets.QLabel(TimeSheets)
        self.weeks_total_label.setObjectName("weeks_total_label")
        self.horizontalLayout_7.addWidget(self.weeks_total_label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.weeks_total = QtWidgets.QLabel(TimeSheets)
        self.weeks_total.setObjectName("weeks_total")
        self.horizontalLayout_7.addWidget(self.weeks_total)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.tabs = QtWidgets.QTabWidget(TimeSheets)
        self.tabs.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid rgb(65, 65, 65);\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; /* move to the right by 5px */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 rgb(65, 65, 65), stop: 0.4 rgb(70, 70, 70),\n"
"                                stop: 0.5 rgb(75, 75, 75), stop: 1.0 rgb(80, 80, 80));\n"
"    border: 2px solid  rgb(65, 65, 65);\n"
"    color: rgb(100, 100, 100);\n"
"    border-bottom-color: rgb(65, 65, 65);\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 rgb(80, 80, 80), stop: 0.4 rgb(85, 85, 85),\n"
"                                stop: 0.5 rgb(90, 90, 90), stop: 1.0 rgb(100, 100, 100));\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color:rgb(80, 80, 80);\n"
"    \n"
"    color: rgb(210, 210, 210);\n"
"    border-bottom-color: rgb(80, 80, 80); /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"")
        self.tabs.setObjectName("tabs")
        self.time_sheets_tab = QtWidgets.QWidget()
        self.time_sheets_tab.setObjectName("time_sheets_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.time_sheets_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.artist_name = QtWidgets.QLabel(self.time_sheets_tab)
        self.artist_name.setStyleSheet("font: 18pt \"SeriaSansPro\";")
        self.artist_name.setObjectName("artist_name")
        self.horizontalLayout.addWidget(self.artist_name)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.whose_timesheets = QtWidgets.QComboBox(self.time_sheets_tab)
        self.whose_timesheets.setObjectName("whose_timesheets")
        self.whose_timesheets.addItem("")
        self.horizontalLayout.addWidget(self.whose_timesheets)
        self.sort_by = QtWidgets.QGroupBox(self.time_sheets_tab)
        self.sort_by.setFlat(True)
        self.sort_by.setObjectName("sort_by")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sort_by)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.person_rdo = QtWidgets.QRadioButton(self.sort_by)
        self.person_rdo.setChecked(True)
        self.person_rdo.setObjectName("person_rdo")
        self.horizontalLayout_2.addWidget(self.person_rdo)
        self.date_rdo = QtWidgets.QRadioButton(self.sort_by)
        self.date_rdo.setChecked(False)
        self.date_rdo.setObjectName("date_rdo")
        self.horizontalLayout_2.addWidget(self.date_rdo)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.order = QtWidgets.QComboBox(self.sort_by)
        self.order.setObjectName("order")
        self.order.addItem("")
        self.order.addItem("")
        self.horizontalLayout_3.addWidget(self.order)
        self.horizontalLayout.addWidget(self.sort_by)
        self.start_date_label = QtWidgets.QLabel(self.time_sheets_tab)
        self.start_date_label.setObjectName("start_date_label")
        self.horizontalLayout.addWidget(self.start_date_label)
        self.start_date = QtWidgets.QDateEdit(self.time_sheets_tab)
        self.start_date.setCalendarPopup(True)
        self.start_date.setObjectName("start_date")
        self.horizontalLayout.addWidget(self.start_date)
        self.end_date_label = QtWidgets.QLabel(self.time_sheets_tab)
        self.end_date_label.setObjectName("end_date_label")
        self.horizontalLayout.addWidget(self.end_date_label)
        self.end_date = QtWidgets.QDateEdit(self.time_sheets_tab)
        self.end_date.setCalendarPopup(True)
        self.end_date.setObjectName("end_date")
        self.horizontalLayout.addWidget(self.end_date)
        self.update_btn = QtWidgets.QPushButton(self.time_sheets_tab)
        self.update_btn.setObjectName("update_btn")
        self.horizontalLayout.addWidget(self.update_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sheet_tree = QtWidgets.QTreeWidget(self.time_sheets_tab)
        self.sheet_tree.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"alternate-background-color: rgb(120, 120, 120);")
        self.sheet_tree.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.sheet_tree.setColumnCount(8)
        self.sheet_tree.setObjectName("sheet_tree")
        self.sheet_tree.headerItem().setText(1, "Project")
        self.sheet_tree.headerItem().setText(2, "Entity")
        self.sheet_tree.headerItem().setText(3, "Task")
        self.sheet_tree.headerItem().setText(4, "Start")
        self.sheet_tree.headerItem().setText(5, "End")
        self.sheet_tree.headerItem().setText(6, "Duration")
        self.sheet_tree.headerItem().setText(7, "Edit")
        self.sheet_tree.header().setVisible(False)
        self.sheet_tree.header().setCascadingSectionResizes(True)
        self.sheet_tree.header().setDefaultSectionSize(120)
        self.sheet_tree.header().setMinimumSectionSize(26)
        self.verticalLayout.addWidget(self.sheet_tree)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.editor_status = QtWidgets.QLabel(self.time_sheets_tab)
        self.editor_status.setObjectName("editor_status")
        self.verticalLayout_2.addWidget(self.editor_status)
        self.editor_progress = QtWidgets.QProgressBar(self.time_sheets_tab)
        self.editor_progress.setStatusTip("")
        self.editor_progress.setStyleSheet("QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(90, 90, 90);\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(224, 149, 0);\n"
"    width: 20px;\n"
"    margin: 1px;\n"
"}")
        self.editor_progress.setProperty("value", 24)
        self.editor_progress.setInvertedAppearance(False)
        self.editor_progress.setObjectName("editor_progress")
        self.verticalLayout_2.addWidget(self.editor_progress)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.excel_rdo = QtWidgets.QRadioButton(self.time_sheets_tab)
        self.excel_rdo.setChecked(True)
        self.excel_rdo.setObjectName("excel_rdo")
        self.horizontalLayout_5.addWidget(self.excel_rdo)
        self.csv_rdo = QtWidgets.QRadioButton(self.time_sheets_tab)
        self.csv_rdo.setObjectName("csv_rdo")
        self.horizontalLayout_5.addWidget(self.csv_rdo)
        self.txt_rdo = QtWidgets.QRadioButton(self.time_sheets_tab)
        self.txt_rdo.setObjectName("txt_rdo")
        self.horizontalLayout_5.addWidget(self.txt_rdo)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.export_btn = QtWidgets.QPushButton(self.time_sheets_tab)
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout_4.addWidget(self.export_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tabs.addTab(self.time_sheets_tab, "")
        self.manual_time = QtWidgets.QWidget()
        self.manual_time.setObjectName("manual_time")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.manual_time)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.new_artist_label = QtWidgets.QLabel(self.manual_time)
        self.new_artist_label.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.new_artist_label.setObjectName("new_artist_label")
        self.verticalLayout_3.addWidget(self.new_artist_label)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.new_project_label = QtWidgets.QLabel(self.manual_time)
        self.new_project_label.setObjectName("new_project_label")
        self.horizontalLayout_9.addWidget(self.new_project_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.new_project = QtWidgets.QComboBox(self.manual_time)
        self.new_project.setMinimumSize(QtCore.QSize(200, 0))
        self.new_project.setObjectName("new_project")
        self.horizontalLayout_9.addWidget(self.new_project)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.new_entity_label = QtWidgets.QLabel(self.manual_time)
        self.new_entity_label.setObjectName("new_entity_label")
        self.horizontalLayout_10.addWidget(self.new_entity_label)
        spacerItem8 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.new_entity = QtWidgets.QComboBox(self.manual_time)
        self.new_entity.setMinimumSize(QtCore.QSize(200, 0))
        self.new_entity.setObjectName("new_entity")
        self.horizontalLayout_10.addWidget(self.new_entity)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.new_task_label = QtWidgets.QLabel(self.manual_time)
        self.new_task_label.setObjectName("new_task_label")
        self.horizontalLayout_11.addWidget(self.new_task_label)
        spacerItem10 = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.new_task = QtWidgets.QComboBox(self.manual_time)
        self.new_task.setMinimumSize(QtCore.QSize(200, 0))
        self.new_task.setObjectName("new_task")
        self.horizontalLayout_11.addWidget(self.new_task)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.new_start_time_label = QtWidgets.QLabel(self.manual_time)
        self.new_start_time_label.setObjectName("new_start_time_label")
        self.horizontalLayout_12.addWidget(self.new_start_time_label)
        spacerItem12 = QtWidgets.QSpacerItem(46, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.new_start_date = QtWidgets.QDateEdit(self.manual_time)
        self.new_start_date.setCalendarPopup(True)
        self.new_start_date.setObjectName("new_start_date")
        self.horizontalLayout_12.addWidget(self.new_start_date)
        self.new_start_time = QtWidgets.QTimeEdit(self.manual_time)
        self.new_start_time.setObjectName("new_start_time")
        self.horizontalLayout_12.addWidget(self.new_start_time)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.new_end_label = QtWidgets.QLabel(self.manual_time)
        self.new_end_label.setObjectName("new_end_label")
        self.horizontalLayout_13.addWidget(self.new_end_label)
        spacerItem14 = QtWidgets.QSpacerItem(52, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem14)
        self.new_end_date = QtWidgets.QDateEdit(self.manual_time)
        self.new_end_date.setCalendarPopup(True)
        self.new_end_date.setObjectName("new_end_date")
        self.horizontalLayout_13.addWidget(self.new_end_date)
        self.new_end_time = QtWidgets.QTimeEdit(self.manual_time)
        self.new_end_time.setObjectName("new_end_time")
        self.horizontalLayout_13.addWidget(self.new_end_time)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem16)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem17)
        self.add_time_btn = QtWidgets.QPushButton(self.manual_time)
        self.add_time_btn.setObjectName("add_time_btn")
        self.horizontalLayout_14.addWidget(self.add_time_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.manual_time)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_14.addWidget(self.cancel_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.tabs.addTab(self.manual_time, "")
        self.verticalLayout_5.addWidget(self.tabs)

        self.retranslateUi(TimeSheets)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TimeSheets)

    def retranslateUi(self, TimeSheets):
        TimeSheets.setWindowTitle(QtWidgets.QApplication.translate("TimeSheets", "Time Sheets", None))
        self.title.setText(QtWidgets.QApplication.translate("TimeSheets", "Time Lord Sheets", None))
        self.todays_total_label.setText(QtWidgets.QApplication.translate("TimeSheets", "Today\'s Hours:", None))
        self.todays_total.setText(QtWidgets.QApplication.translate("TimeSheets", "%0.2f", None))
        self.weeks_total_label.setText(QtWidgets.QApplication.translate("TimeSheets", "Week\'s Hours: ", None))
        self.weeks_total.setText(QtWidgets.QApplication.translate("TimeSheets", "%0.2f", None))
        self.artist_name.setText(QtWidgets.QApplication.translate("TimeSheets", "Artist", None))
        self.whose_timesheets.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#000000;\">List of available people and time sheets</span></p></body></html>", None))
        self.whose_timesheets.setItemText(0, QtWidgets.QApplication.translate("TimeSheets", "My Timesheets", None))
        self.sort_by.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0a0a0a;\">Sorting Options</span></p></body></html>", None))
        self.sort_by.setTitle(QtWidgets.QApplication.translate("TimeSheets", "Sort By", None))
        self.person_rdo.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0b0b0b;\">Sort By Person/Date</span></p></body></html>", None))
        self.person_rdo.setText(QtWidgets.QApplication.translate("TimeSheets", "Person", None))
        self.date_rdo.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0b0b0b;\">Sort By Date/Person</span></p></body></html>", None))
        self.date_rdo.setText(QtWidgets.QApplication.translate("TimeSheets", "Date", None))
        self.order.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0a0a0a;\">Dates in Ascending or Descending Order</span></p></body></html>", None))
        self.order.setItemText(0, QtWidgets.QApplication.translate("TimeSheets", "Ascending", None))
        self.order.setItemText(1, QtWidgets.QApplication.translate("TimeSheets", "Decending", None))
        self.start_date_label.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0a0a0a;\">Start Search Date</span></p></body></html>", None))
        self.start_date_label.setText(QtWidgets.QApplication.translate("TimeSheets", "Start Date", None))
        self.start_date.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0a0a0a;\">Start Search Date</span></p></body></html>", None))
        self.end_date_label.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0a0a0a;\">End Search Date</span></p></body></html>", None))
        self.end_date_label.setText(QtWidgets.QApplication.translate("TimeSheets", "End Date", None))
        self.end_date.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0a0a0a;\">End Search Date</span></p></body></html>", None))
        self.update_btn.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0b0b0b;\">Update the Sheets</span></p></body></html>", None))
        self.update_btn.setText(QtWidgets.QApplication.translate("TimeSheets", "Update", None))
        self.sheet_tree.headerItem().setText(0, QtWidgets.QApplication.translate("TimeSheets", "Timesheet", None))
        self.editor_status.setText(QtWidgets.QApplication.translate("TimeSheets", "TextLabel", None))
        self.excel_rdo.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0a0a0a;\">Export EXCEL sheet</span></p></body></html>", None))
        self.excel_rdo.setText(QtWidgets.QApplication.translate("TimeSheets", "Excel", None))
        self.csv_rdo.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0a0a0a;\">Export CSV Sheet</span></p></body></html>", None))
        self.csv_rdo.setText(QtWidgets.QApplication.translate("TimeSheets", "CSV", None))
        self.txt_rdo.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0a0a0a;\">Export TXT File</span></p></body></html>", None))
        self.txt_rdo.setText(QtWidgets.QApplication.translate("TimeSheets", "TXT", None))
        self.export_btn.setToolTip(QtWidgets.QApplication.translate("TimeSheets", "<html><head/><body><p><span style=\" color:#0a0a0a;\">Run the export</span></p></body></html>", None))
        self.export_btn.setText(QtWidgets.QApplication.translate("TimeSheets", "Export", None))
        self.tabs.setTabText(self.tabs.indexOf(self.time_sheets_tab), QtWidgets.QApplication.translate("TimeSheets", "Time Sheets", None))
        self.new_artist_label.setText(QtWidgets.QApplication.translate("TimeSheets", "Artist", None))
        self.new_project_label.setText(QtWidgets.QApplication.translate("TimeSheets", "Project", None))
        self.new_entity_label.setText(QtWidgets.QApplication.translate("TimeSheets", "Entity", None))
        self.new_task_label.setText(QtWidgets.QApplication.translate("TimeSheets", "Task", None))
        self.new_start_time_label.setText(QtWidgets.QApplication.translate("TimeSheets", "Start", None))
        self.new_end_label.setText(QtWidgets.QApplication.translate("TimeSheets", "End", None))
        self.add_time_btn.setText(QtWidgets.QApplication.translate("TimeSheets", "Add", None))
        self.cancel_btn.setText(QtWidgets.QApplication.translate("TimeSheets", "Cancel", None))
        self.tabs.setTabText(self.tabs.indexOf(self.manual_time), QtWidgets.QApplication.translate("TimeSheets", "Manual Time Card", None))

