# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sleep\OneDrive\Documents\Scripts\Python\Maya\RiggingTools\attribute_machine\ui\attribute_machine_ui.ui'
#
# Created: Thu Sep 20 22:18:41 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_machine(object):
    def setupUi(self, machine):
        machine.setObjectName("machine")
        machine.resize(853, 587)
        machine.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(230, 230, 230);")
        self.verticalLayout_3 = QtGui.QVBoxLayout(machine)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtGui.QLabel(machine)
        self.label.setStyleSheet("font: 75 22pt \"BankGothic\";")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.modes_group = QtGui.QGroupBox(machine)
        self.modes_group.setMinimumSize(QtCore.QSize(0, 75))
        self.modes_group.setObjectName("modes_group")
        self.layoutWidget = QtGui.QWidget(self.modes_group)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 481, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_mode = QtGui.QRadioButton(self.layoutWidget)
        self.add_mode.setChecked(True)
        self.add_mode.setObjectName("add_mode")
        self.horizontalLayout.addWidget(self.add_mode)
        self.set_mode = QtGui.QRadioButton(self.layoutWidget)
        self.set_mode.setObjectName("set_mode")
        self.horizontalLayout.addWidget(self.set_mode)
        self.connect_mode = QtGui.QRadioButton(self.layoutWidget)
        self.connect_mode.setObjectName("connect_mode")
        self.horizontalLayout.addWidget(self.connect_mode)
        self.command_mode = QtGui.QRadioButton(self.layoutWidget)
        self.command_mode.setObjectName("command_mode")
        self.horizontalLayout.addWidget(self.command_mode)
        self.verticalLayout_3.addWidget(self.modes_group)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.out_attr = QtGui.QGroupBox(machine)
        self.out_attr.setMinimumSize(QtCore.QSize(0, 250))
        self.out_attr.setObjectName("out_attr")
        self.verticalLayoutWidget = QtGui.QWidget(self.out_attr)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 311, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.out_attr_list = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.out_attr_list.setContentsMargins(0, 0, 0, 0)
        self.out_attr_list.setObjectName("out_attr_list")
        self.horizontalLayout_2.addWidget(self.out_attr)
        self.ConnectionLine = QtGui.QFrame(machine)
        self.ConnectionLine.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ConnectionLine.setFrameShadow(QtGui.QFrame.Raised)
        self.ConnectionLine.setLineWidth(4)
        self.ConnectionLine.setObjectName("ConnectionLine")
        self.horizontalLayout_2.addWidget(self.ConnectionLine)
        self.in_attr = QtGui.QGroupBox(machine)
        self.in_attr.setObjectName("in_attr")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.in_attr)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 311, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.in_attr_list = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.in_attr_list.setContentsMargins(0, 0, 0, 0)
        self.in_attr_list.setObjectName("in_attr_list")
        self.horizontalLayout_2.addWidget(self.in_attr)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.values = QtGui.QPlainTextEdit(machine)
        self.values.setFrameShape(QtGui.QFrame.Box)
        self.values.setLineWidth(2)
        self.values.setDocumentTitle("")
        self.values.setObjectName("values")
        self.verticalLayout_3.addWidget(self.values)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.do_it = QtGui.QPushButton(machine)
        self.do_it.setObjectName("do_it")
        self.horizontalLayout_3.addWidget(self.do_it)
        self.dont_do_it = QtGui.QPushButton(machine)
        self.dont_do_it.setObjectName("dont_do_it")
        self.horizontalLayout_3.addWidget(self.dont_do_it)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(machine)
        QtCore.QMetaObject.connectSlotsByName(machine)

    def retranslateUi(self, machine):
        machine.setWindowTitle(QtGui.QApplication.translate("machine", "Attribute Machine", None))
        self.label.setText(QtGui.QApplication.translate("machine", "Attribute Machine", None))
        self.modes_group.setTitle(QtGui.QApplication.translate("machine", "Modes", None))
        self.add_mode.setText(QtGui.QApplication.translate("machine", "Add", None))
        self.set_mode.setText(QtGui.QApplication.translate("machine", "Set", None))
        self.connect_mode.setText(QtGui.QApplication.translate("machine", "Connect", None))
        self.command_mode.setText(QtGui.QApplication.translate("machine", "Command", None))
        self.out_attr.setTitle(QtGui.QApplication.translate("machine", "Out Attribute", None))
        self.in_attr.setTitle(QtGui.QApplication.translate("machine", "In Attributes", None))
        self.do_it.setText(QtGui.QApplication.translate("machine", "Do It", None))
        self.dont_do_it.setText(QtGui.QApplication.translate("machine", "Don\'t Do It", None))

